version: '3.3'
services:
  athena:
    image: athena-api:v1
    working_dir: /opt
    command: java -Djava.awt.headless=true -Dspring.profiles.active=dev -jar athena-api.war
    networks:
      - catech-networks
    ports:
      - "8080:8080"
networks:
  catech-networks:
    driver: bridge
